export default Object.freeze({
  foodFavicon: "https://chocofood.kz/favicon.png",
  lifeFavicon:
    "https://chocolife.object.pscloud.io/static/angular/assets/favicons/new/favicon-32x32.png",
  cities: [
    "Алматы",
    "Актау",
    "Актобе",
    "Астана",
    "Атырау",
    "Караганда",
    "Каскелен",
    "Кокшетау",
    "Костанай",
    "Кульджинский тракт",
    "Кунаев",
    "Кызылорда",
    "Ленгер",
    "Павлодар",
    "Петропавловск",
    "село Отеген батыр",
    "Семей",
    "Талгар",
    "Талдыкорган",
    "Тараз",
    "Темиртау",
    "Уральск",
    "Усть-Каменогорск",
    "Шымкент",
    "Экибастуз",
  ],
  menuOptions: [
    {
      id: 1,
      title: "Показать все заказы",
      icon: "fas fa-clipboard-list",
      route: "foodOrders",
    },
    {
      id: 2,
      title: "Мои бонусы",
      icon: "fas fa-coins",
      route: "foodBonuses",
    },
    {
      id: 3,
      title: "Мои карты",
      icon: "fas fa-credit-card",
      route: "foodCards",
    },
    {
      id: 4,
      title: "Мои адреса",
      icon: "fas fa-map-marker-alt",
      route: "foodAddresses",
    },
    { id: 0, title: "Выйти из аккаунта", icon: "fas fa-power-off" },
  ],
});
